# 6장. 텍스트 다루기

이 노트북을 주피터 노트북 뷰어(nbviewer.jupyter.org)로 보거나 구글 코랩(colab.research.google.com)에서 실행할 수 있습니다.

<table align="left">
  <td>
    <a target="_blank" href="https://nbviewer.org/github/rickiepark/machine-learning-with-python-cookbook/blob/master/06.ipynb"><img src="https://jupyter.org/assets/share.png" width="60" />주피터 노트북 뷰어로 보기</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/machine-learning-with-python-cookbook/blob/master/06.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩(Colab)에서 실행하기</a>
  </td>
</table>

## 6.1 텍스트 정제

In [1]:
# 텍스트를 만듭니다.
text_data = ["   Interrobang. By Aishwarya Henriette     ",
             "Parking And Going. By Karl Gautier",
             "    Today Is The night. By Jarek Prakash   "]

# 공백 문자를 제거합니다.
strip_whitespace = [string.strip() for string in text_data]

# 텍스트를 확인합니다.
strip_whitespace

['Interrobang. By Aishwarya Henriette',
 'Parking And Going. By Karl Gautier',
 'Today Is The night. By Jarek Prakash']

In [2]:
# 마침표를 제거합니다.
remove_periods = [string.replace(".", "") for string in strip_whitespace]

# 텍스트를 확인합니다.
remove_periods

['Interrobang By Aishwarya Henriette',
 'Parking And Going By Karl Gautier',
 'Today Is The night By Jarek Prakash']

In [3]:
# 함수를 만듭니다.
def capitalizer(string: str) -> str: # 매개변수 s가 문자열(str)이어야 한다는 타입 힌트 #이 함수가 문자열을 반환한다는 타입 힌트
    return string.upper()

# 함수를 적용합니다.
[capitalizer(string) for string in remove_periods]

['INTERROBANG BY AISHWARYA HENRIETTE',
 'PARKING AND GOING BY KARL GAUTIER',
 'TODAY IS THE NIGHT BY JAREK PRAKASH']

In [1]:
# 라이브러리를 임포트합니다.
import re

# 함수를 만듭니다.
def replace_letters_with_X(string: str) -> str:
    return re.sub(r"[a-zA-Z]", "X", string)


#re.sub(치환할 정규식 {문자열 또는 컴파일된 객체}, 치환할 문자열, 검색/치환할 원본 문자열
# r""는 raw string(원시 문자열)이고, 정규식을 쓸 때 사용
# r"..."은 문자열 안의 이스케이프 문자(예: \n, \t)를 그대로 처리
# 함수를 적용합니다.
[replace_letters_with_X(string) for string in remove_periods]

NameError: name 'remove_periods' is not defined

## 6.2 HTML 파싱과 정제

In [5]:
# 라이브러리를 임포트합니다.
from bs4 import BeautifulSoup

# 예제 HTML 코드를 만듭니다.
html = """
       <div class='full_name'><span style='font-weight:bold'>
       Masego</span> Azra</div>"
       """

# html을 파싱합니다.
soup = BeautifulSoup(html, "lxml")

# "full_name" 이름의 클래스를 가진 div를 찾아 텍스트를 출력합니다.
soup.find("div", { "class" : "full_name" }).text

'\n       Masego Azra'

## 6.3 구둣점 삭제

In [6]:
# 라이브러리를 임포트합니다.
import unicodedata  # 전 세계 모든 문자(기호, 이모지 포함)를 하나의 표준 코드로 표현 # ASCII 등.
import sys  # 입출력, 인자, 종료 등 시스템 관련 기능 제공

# 텍스트를 만듭니다.
text_data = ['Hi!!!! I. Love. This. Song....',
             '10000% Agree!!!! #LoveIT',
             'Right?!?!']

# 구두점 문자로 이루어진 딕셔너리를 만듭니다.
punctuation = dict.fromkeys(i for i in range(sys.maxunicode)
                            #파이썬이 지원하는 유니코드 문자 중 가장 큰 코드 포인트 번호
                            if unicodedata.category(chr(i)).startswith('P'))

# 문자열의 구두점을 삭제합니다.
[string.translate(punctuation) for string in text_data]

['Hi I Love This Song', '10000 Agree LoveIT', 'Right']

문자   	유니코드 코드포인트	10진수	함수
'A'  	U+0041	65	        chr(65) → 'A'
'가'	U+AC00	44032	    chr(44032) → '가'


1.dict.fromkeys()를 통해 딕셔너리 생성
구문:

dict.fromkeys(이터러블)
의미: 이터러블의 요소들을 key로, 값은 모두 기본값 None으로 딕셔너리 생성

예시:

python

dict.fromkeys([1, 2, 3])
👉 {1: None, 2: None, 3: None}

2. i in range(sys.maxunicode)로 유니코드 전체 범위를 순회
sys.maxunicode는 1114111 (0x10FFFF) → 유니코드에서 쓸 수 있는 최대 코드포인트

i는 정수 (예: 33, 46 등)

3. chr(i)는 정수 → 문자 변환 함수
💬 너 질문: char()은 문자를 정수로 바꾸나? → ❌ 아니야
→ 정답: chr()는 정수 → 문자
→ 반대는 ord() : 문자 → 정수

함수	설명	예시
chr(65)	65를 문자로 → 'A'
ord('A')	'A'를 정수로 → 65

4. unicodedata.category(chr(i))로 문자 분류 조회
유니코드 문자를 범주(category)로 분류함

예:

'A' → 'Lu' (대문자)

'!' → 'Po' (기타 구두점)

',' → 'Po'

→ 즉, chr(i)가 구두점이면 'P'로 시작하는 문자열을 반환

5. .startswith('P')는 그 카테고리가 구두점 계열인지 확인
'P'로 시작하는 것만 골라냄:

Po (기타)

Pd (대시)

Ps (시작 괄호)

등등


자료형 : 문자 to 딕셔너리 ( 키 : 숫자 , 값 : none )
정의 : 구두점을 전부 replace하기 힘들기 때문에, 유니코드 표현 p로 시작하는 것을 찾아 삭하자
고려 : 유니코드는 p l과 같은 구두점, 대문자 계열이 있고, 각각 번호가 부여됨. , 최대 유니코드는 maxunicode
필요한 객체 : 입력값, 구두점을 찾는 객체
필요한 함수 : sys (최대 유니코드 정수) , unicode 전세계모든 유니코드 ( 문자 'A' , 유니코드 U_001, 코드 포인트 65, 10진수? char(정수 요소 값들) -> 65로 변경),  category(유니코드 범주) , 삭제? translate(객체)
조건문 & 로직
    1. 임포트한다.
    2. 모든 구두점들을 찾기 위해, 최대 유니코드 정수를 순회해서 코드 포인트를 찾고, 이 정수를 문자로 변경해서 문자가 p 계열의 범주인지 찾는다.
    3. 삭제한다.


## 6.4 텍스트 토큰화

In [7]:
# 구두점 데이터를 다운로드합니다.
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/haesun/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [8]:
# 라이브러리를 임포트합니다.
from nltk.tokenize import word_tokenize

# 텍스트를 만듭니다.
string = "The science of today is the technology of tomorrow"

# 단어를 토큰으로 나눕니다.
word_tokenize(string)

['The', 'science', 'of', 'today', 'is', 'the', 'technology', 'of', 'tomorrow']

In [9]:
# 라이브러리를 임포트합니다.
from nltk.tokenize import sent_tokenize

# 텍스트를 만듭니다.
string = "The science of today is the technology of tomorrow. Tomorrow is today."

# 문장으로 나눕니다.
sent_tokenize(string)

['The science of today is the technology of tomorrow.', 'Tomorrow is today.']

## 6.5 불용어 삭제

In [10]:
# 불용어 데이터를 다운로드합니다.
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/haesun/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [11]:
# 라이브러리를 임포트합니다.
from nltk.corpus import stopwords

# 단어 토큰을 만듭니다.
tokenized_words = ['i',
                   'am',
                   'going',
                   'to',
                   'go',
                   'to',
                   'the',
                   'store',
                   'and',
                   'park']

# 불용어를 적재합니다.
stop_words = stopwords.words('english')

# 불용어를 삭제합니다.
[word for word in tokenized_words if word not in stop_words]

['going', 'go', 'store', 'park']

In [12]:
# 불용어를 확인합니다.
stop_words[:5]

['i', 'me', 'my', 'myself', 'we']

In [13]:
stopwords.abspath

<bound method CorpusReader.abspath of <WordListCorpusReader in '/home/haesun/nltk_data/corpora/stopwords'>>

## 붙임

In [14]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

len(ENGLISH_STOP_WORDS), len(stop_words)

(318, 179)

In [15]:
list(ENGLISH_STOP_WORDS)[:5]

['serious', 'side', 'thru', 'hers', 'keep']

## 6.6 어간 추출

In [16]:
# 라이브러리를 임포트합니다.
from nltk.stem.porter import PorterStemmer

# 단어 토큰을 만듭니다.
tokenized_words = ['i', 'am', 'humbled', 'by', 'this', 'traditional', 'meeting']

# 어간 추출기를 만듭니다.
porter = PorterStemmer()

# 어간 추출기를 적용합니다.
[porter.stem(word) for word in tokenized_words]

['i', 'am', 'humbl', 'by', 'thi', 'tradit', 'meet']

## 6.7 품사 태깅

In [17]:
# 태거를 다운로드합니다.
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/haesun/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [18]:
# 라이브러리를 임포트합니다.
from nltk import pos_tag
from nltk import word_tokenize

# 텍스트를 만듭니다.
text_data = "Chris loved outdoor running"

# 사전 훈련된 품사 태깅을 사용합니다.
text_tagged = pos_tag(word_tokenize(text_data))

# 품사를 확인합니다.
text_tagged

[('Chris', 'NNP'), ('loved', 'VBD'), ('outdoor', 'RP'), ('running', 'VBG')]

In [19]:
# 단어를 필터링합니다.
[word for word, tag in text_tagged if tag in ['NN','NNS','NNP','NNPS'] ]

['Chris']

In [20]:
from sklearn.preprocessing import MultiLabelBinarizer

# 텍스트를 만듭니다.
tweets = ["I am eating a burrito for breakfast",
          "Political science is an amazing field",
          "San Francisco is an awesome city"]

# 빈 리스트를 만듭니다.
tagged_tweets = []

# 각 단어와 트윗을 태깅합니다.
for tweet in tweets:
    tweet_tag = nltk.pos_tag(word_tokenize(tweet))
    tagged_tweets.append([tag for word, tag in tweet_tag])

# 원-핫 인코딩을 사용하여 태그를 특성으로 변환합니다.
one_hot_multi = MultiLabelBinarizer()
one_hot_multi.fit_transform(tagged_tweets)

array([[1, 1, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 1]])

In [21]:
# 특성 이름을 확인합니다.
one_hot_multi.classes_

array(['DT', 'IN', 'JJ', 'NN', 'NNP', 'PRP', 'VBG', 'VBP', 'VBZ'],
      dtype=object)

In [22]:
# 브라운 코퍼스를 다운로드합니다.
import nltk
nltk.download('brown')

[nltk_data] Downloading package brown to /home/haesun/nltk_data...
[nltk_data]   Package brown is already up-to-date!


True

In [23]:
# 라이브러리를 임포트합니다.
from nltk.corpus import brown
from nltk.tag import UnigramTagger
from nltk.tag import BigramTagger
from nltk.tag import TrigramTagger

# 브라운 코퍼스에서 텍스트를 추출한 다음 문장으로 나눕니다.
sentences = brown.tagged_sents(categories='news')

# 4,000개의 문장은 훈련용으로 623개는 테스트용으로 나눕니다.
train = sentences[:4000]
test = sentences[4000:]

# 백오프 태그 객체를 만듭니다.
unigram = UnigramTagger(train)
bigram = BigramTagger(train, backoff=unigram)
trigram = TrigramTagger(train, backoff=bigram)

# 정확도를 확인합니다.
trigram.evaluate(test)

0.8174734002697437

## 붙임

In [24]:
# 코랩에서 실행하는 경우 다음 주석을 제거하고 실행하세요.
#!pip install konlpy

In [25]:
# 최신 버전의 tweepy 패키지가 설치될 경우 konlpy에서 StreamListener가 없다는 에러가 발생하므로 
# 3.10버전을 설치해 주세요. pip install tweepy==3.10
from konlpy.tag import Okt
okt = Okt()

In [26]:
text = '태양계는 지금으로부터 약 46억 년 전, 거대한 분자 구름의 일부분이 중력 붕괴를 일으키면서 형성되었다'

okt.pos(text)

[('태양계', 'Noun'),
 ('는', 'Josa'),
 ('지금', 'Noun'),
 ('으로부터', 'Josa'),
 ('약', 'Noun'),
 ('46억', 'Number'),
 ('년', 'Noun'),
 ('전', 'Noun'),
 (',', 'Punctuation'),
 ('거대한', 'Adjective'),
 ('분자', 'Noun'),
 ('구름', 'Noun'),
 ('의', 'Josa'),
 ('일부분', 'Noun'),
 ('이', 'Josa'),
 ('중력', 'Noun'),
 ('붕괴', 'Noun'),
 ('를', 'Josa'),
 ('일으키면서', 'Verb'),
 ('형성', 'Noun'),
 ('되었다', 'Verb')]

In [27]:
okt.morphs(text)

['태양계',
 '는',
 '지금',
 '으로부터',
 '약',
 '46억',
 '년',
 '전',
 ',',
 '거대한',
 '분자',
 '구름',
 '의',
 '일부분',
 '이',
 '중력',
 '붕괴',
 '를',
 '일으키면서',
 '형성',
 '되었다']

In [28]:
okt.nouns(text)

['태양계', '지금', '약', '년', '전', '분자', '구름', '일부분', '중력', '붕괴', '형성']

## 6.8 텍스트를 BoW로 인코딩하기

In [29]:
# 라이브러리를 임포트합니다.
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

# 텍스트를 만듭니다.
text_data = np.array(['I love Brazil. Brazil!',
                      'Sweden is best',
                      'Germany beats both'])

# BoW 특성 행렬을 만듭니다.
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

# 특성 행렬을 확인합니다.
bag_of_words

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [30]:
bag_of_words.toarray()

array([[0, 0, 0, 2, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 0]])

In [31]:
# 특성 이름을 확인합니다.
# 사이킷런 0.24 버전 이하일 경우 get_features_names() 메서드를 사용하세요.
count.get_feature_names_out()

array(['beats', 'best', 'both', 'brazil', 'germany', 'is', 'love',
       'sweden'], dtype=object)

In [32]:
# 옵션을 지정하여 특성 행렬을 만듭니다.
count_2gram = CountVectorizer(ngram_range=(1,2),
                              stop_words="english",
                              vocabulary=['brazil'])
bag = count_2gram.fit_transform(text_data)

# 특성 행렬을 확인합니다.
bag.toarray()

array([[2],
       [0],
       [0]])

In [33]:
# 1-그램과 2-그램을 확인합니다.
count_2gram.vocabulary_

{'brazil': 0}

## 6.9 단어 중요도에 가중치 부여하기

In [34]:
# 라이브러리를 임포트합니다.
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

# 텍스트를 만듭니다.
text_data = np.array(['I love Brazil. Brazil!',
                      'Sweden is best',
                      'Germany beats both'])

# tf-idf 특성 행렬을 만듭니다.
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

# tf-idf 특성 행렬을 확인합니다.
feature_matrix

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [35]:
# tf-idf 특성 행렬을 밀집 배열로 확인합니다.
feature_matrix.toarray()

array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])

In [36]:
# 특성 이름을 확인합니다.
tfidf.vocabulary_

{'love': 6,
 'brazil': 3,
 'sweden': 7,
 'is': 5,
 'best': 1,
 'germany': 4,
 'beats': 0,
 'both': 2}